env:
  browser: true
  es2021: true
  node: true
  jest: true
plugins:
  - react
  - "@typescript-eslint"
extends:
  - eslint:recommended
  - airbnb
  - plugin:react/recommended
  - plugin:react/jsx-runtime
  - plugin:@typescript-eslint/recommended
  - plugin:import/typescript
parser: "@typescript-eslint/parser"
parserOptions:
  ecmaFeatures:
    jsx: true
  ecmaVersion: latest
  sourceType: module
rules:
  "@typescript-eslint/ban-ts-comment": 1
  quotes: [2, double]
  comma-dangle: 1 # fix for prettier (no comma for args)
  indent: 1
  object-curly-newline: [1, { multiline: true, consistent: true }]
  max-len: [1, { code: 100 }]
  operator-linebreak: 1
  import/prefer-default-export: 0
  import/extensions: 0
  react/jsx-filename-extension: [1, { extensions: [.tsx, .ts] }]
  react/button-has-type: 0
  arrow-body-style: 1 # fix
  implicit-arrow-linebreak: 1 # fix
  react/function-component-definition: 1 # fix
  react/no-array-index-key: 1 # fix
  react/jsx-curly-newline: 1 # fix
  react/jsx-one-expression-per-line: 1 # fix
