env:
  browser: true
  es2021: true
  node: true
  jest: true
plugins:
  - react
  - "@typescript-eslint"
extends:
  - eslint:recommended
  - airbnb
  - plugin:react/recommended
  - plugin:react/jsx-runtime
  - plugin:@typescript-eslint/recommended
  - plugin:import/typescript
parser: "@typescript-eslint/parser"
parserOptions:
  ecmaFeatures:
    jsx: true
  ecmaVersion: latest
  sourceType: module
ignorePatterns: [_NOTES, build]
rules:
  "@typescript-eslint/ban-ts-comment": 1
  quotes: [2, double]
  comma-dangle:
    [
      1,
      {
        arrays: always-multiline,
        objects: always-multiline,
        imports: always-multiline,
        exports: always-multiline,
        functions: never,
      },
    ]
  indent: 1
  object-curly-newline: [1, { multiline: true, consistent: true }]
  max-len: [1, { code: 100 }]
  operator-linebreak: 1
  no-confusing-arrow: 1 # fix
  function-paren-newline: 1 # fix
  import/prefer-default-export: 0
  import/extensions: 0
  react/jsx-filename-extension: [1, { extensions: [.tsx, .ts] }]
  react/button-has-type: 0
  react/jsx-one-expression-per-line: [0, { allow: single-child }]
  arrow-body-style: 2
  implicit-arrow-linebreak: 1 # fix
  react/function-component-definition:
    [2, { namedComponents: arrow-function, unnamedComponents: arrow-function }]
  react/no-array-index-key: 1 # fix
  react/jsx-curly-newline: 1 # fix
  no-shadow: 0
  "@typescript-eslint/no-shadow": 2
